### ISSUE TITLE
When Clicking the Verify Store Keys button => dark overlay

### ISSUE THREAD

**Issue by andwah** [Starcounter/WarehouseClient#11]
When Clicking the Verify Store Keys button in the Warehouse client Settings page when you have an invalid store key the dialog window is not shown. only the dark overlay.

**Comment by miyconst** [comment]
How to reproduce the issue? I am not able to.

**Comment by andwah** [comment]
go to http://warehouse.starcounter.com/launcher/settings
Add a store key "1234"
Click the VERIFY STORE KEYS button

**Comment by miyconst** [comment]
There is already a store `1234`. Click the button does not show any dialog or shadow at all.

**Comment by andwah** [comment]
come over and ill show you :-)

**Comment by miyconst** [comment]
@andwah sorry I was not able to come that time, is the issue still there? Let's try to solve it.

**Comment by andwah** [comment]
I think this was the cause https://github.com/Starcounter/starcounter-include/issues/13 and it's now fixed so im closing this one.
