### ISSUE TITLE
Incorrect CSS BEM

### ISSUE THREAD

**Issue by warpech** [Starcounter/WarehouseClient#12]
Classes like `.warehouse-client-box__items__item__body__thumb__body` in https://github.com/Starcounter/WarehouseClient/blob/77e9d0d1d077f679ba117793e9b42b9ab7a5140b/src/wwwroot/WarehouseClient/css/styles.css are not correct BEM.

In BEM, there might be only one Element section (`__*`) and zero or one Modifier section `(--*)`

**Comment by miyconst** [comment]
Done. Thank you for noting it.
