### ISSUE TITLE
Change `@w` to `{?}` in UriMapping handlers

### ISSUE THREAD

**Issue by warpech** [Starcounter/WarehouseClient#13]
Since Starcounter 2.2, `{?}` should be used instead of `@w` in `OntologyMap` according to the [release notes](http://starcounter.io/starcounter-2-2-release-notes/).

Old usage found on line: https://github.com/Starcounter/WarehouseClient/blob/58d2124b9aa1406c6a217fba6612963157895029/src/Program.cs#L94

**Comment by miyconst** [comment]
Done.
