### ISSUE TITLE
Add My Playgrounds page where user can manage their playgrounds

### ISSUE THREAD

**Issue by miyconst** [Starcounter/WarehouseClient#15]
User should be able to:

- Delete a playground.
- Create a playground.
- Mark a playground as an active.

**Comment by andwah** [comment]
First and simple implementation done. (gui part need some more work).

![image](https://cloud.githubusercontent.com/assets/2656996/18129947/466693ee-6f8d-11e6-9092-0d7d5eccd561.png)
